@startuml
'https://plantuml.com/activity-diagram-beta

title School Facility Rental - Activity
|Renter|
start
:Choose facility, date, event;
|Website|
:Check availability;
if (available?) then (yes)
    |Renter|
    :Enter contact information;
    :Submit request;
    |Website|
    :Create request;
    |School Staff|
    :Review request;
    if (approved?) then (approved)
        |Renter|
        :Send Payment;
        if (succeeds?) then (success)
            |Website|
            :Save booking;
            :Send confirmation email;
            stop
        else (fail)
            |Website|
            :Record payment failure;
            :Send payment failure email;
            stop
        endif
    else (rejected)
        |Website|
        :Send rejection email;
        stop
    endif
else (no)
    |Website|
    :Show not available;
    stop
endif
|School Staff|

@enduml
